<a href='https://www.hexnbit.com/'> <img src='hexnbit.png'/> </a>

# NumPy 

NumPy is the fundamental package for scientific computing with Python. All the other scientific computing libraries like Pandas, OpenCV, Scikit-Learn use NumPy.
Some of the included contents of NumPy are:

  - a powerful N-dimensional array object
  - sophisticated (broadcasting) functions
  - tools for integrating C/C++ and Fortran code
  - useful linear algebra, Fourier transform, and random number capabilities

Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. Arbitrary data-types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of databases.

NumPy is licensed under the [BSD](http://www.numpy.org/license.html#license) license, enabling reuse with few restrictions.

https://numpy.org/devdocs/user/quickstart.html

### Applications
  - Artificial Intelligence
  - Machine Learning
  - Data Science
  - Signal Processing
  - Image Processing etc

## Installation

*We hope that you have installed Python using the Anaconda distribution. This will make sure that all the dependencies work with conda install. Although, NumPy should pre-bundled with Anaconda, just to ensure that you have the latest version, install NumPy by opening your terminal(for MAC Users) or ANACONDA Command Prompt(for Windows Users) and type the following command*
    
    conda install numpy
    
**If you are unable to install ANACONDA due to restrictions, please refer to [Numpy's official documentation on installation steps.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**

## Importing NumPy Package for use

Once NumPy Package is installed successfully, you can import it to the current Python session using the following code:

In [1]:
import numpy as np        # Call the NumPy package using np, here np is just for sake of simplicity

# Intro to Arrays in NumPy

Numpy has a lots of built-in functions that are useful for Data Scientists & Python Programmers.

We shall cover some of the most important topics in Numpy: 

  - Arrays ( using Vectors & Matrices ) 
  - Number Generation Concepts

# Numpy Arrays

NumPy arrays are the one of the most widely used data structuring techniques used in the field of AI, ML and Image Processing. 

Numpy arrays are of two types: Vectors and Matrices. 

Vectors are 1-dimensional

## Creating simple NumPy Array Structures

We can create a simple Array by using a list of values or a list of "List of values".

In [2]:
simple_list = [101,102,103,104,105,106,107,108,109,110]    # List of Values
print(type(simple_list))
print(simple_list)

<class 'list'>
[101, 102, 103, 104, 105, 106, 107, 108, 109, 110]


In [3]:
np_simple_list=np.array(simple_list)    # List of values converted to NumPy type array
print(type(np_simple_list))             # Check type of data
print(np_simple_list)

<class 'numpy.ndarray'>
[101 102 103 104 105 106 107 108 109 110]


In [4]:
simple_list_of_lists = [[10,11,12],[20,21,22],[30,31,32]]   # List of "List of Values"
print(simple_list_of_lists)

[[10, 11, 12], [20, 21, 22], [30, 31, 32]]


In [5]:
print(np.array(simple_list_of_lists))

[[10 11 12]
 [20 21 22]
 [30 31 32]]


In [6]:
row_vector=np.array([1,2,3])
print(row_vector)

[1 2 3]


In [7]:
column_vector=np.array([[1],[2],[3]])
print(column_vector)

[[1]
 [2]
 [3]]


We can also generate arrays using various built-in methods

### arange

Return evenly spaced values within a given interval as input.

In [8]:
array1=(np.arange(0,20))   # Return values 0 to 19. Start value is 0 which is included, 
                         #the stop value provided is 20 which is not included
                         # if one parameter is provided, the start value is considered to be 0 by default.
print(type(array1))
print(array1)

<class 'numpy.ndarray'>
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [9]:
print(np.arange(0,20,4))  # Specify start, stop and step values as input

[ 0  4  8 12 16]


### zeros and ones

Generate arrays of 0's or 1's

In [10]:
print(np.zeros(10))            # Specify the count of 0's required in the array

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [11]:
print(np.zeros((4,3)))         # Specify the number of rows by columns - 4 rows and 3 cols in this example

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [12]:
print(np.ones(10))            # Specify the count of 1's required in the array

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [13]:
print(np.ones((4,5)))         # Specify the number of rows by columns - 4 rows and 5 cols in this example

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


### full
fills a defined value into array

In [14]:
filled_arry=np.full((4,4),fill_value=7)   # Fills 4x4 array with value 7
print(filled_arry)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


### linspace
Return evenly spaced numbers over a specified interval.

In [15]:
print(np.linspace(0,20,5))   # Specify the start, stop and number values needed between them.
                             # Please note the stop value is also considered in this case

[ 0.  5. 10. 15. 20.]


In [16]:
print(np.linspace(0,20,100))

[ 0.          0.2020202   0.4040404   0.60606061  0.80808081  1.01010101
  1.21212121  1.41414141  1.61616162  1.81818182  2.02020202  2.22222222
  2.42424242  2.62626263  2.82828283  3.03030303  3.23232323  3.43434343
  3.63636364  3.83838384  4.04040404  4.24242424  4.44444444  4.64646465
  4.84848485  5.05050505  5.25252525  5.45454545  5.65656566  5.85858586
  6.06060606  6.26262626  6.46464646  6.66666667  6.86868687  7.07070707
  7.27272727  7.47474747  7.67676768  7.87878788  8.08080808  8.28282828
  8.48484848  8.68686869  8.88888889  9.09090909  9.29292929  9.49494949
  9.6969697   9.8989899  10.1010101  10.3030303  10.50505051 10.70707071
 10.90909091 11.11111111 11.31313131 11.51515152 11.71717172 11.91919192
 12.12121212 12.32323232 12.52525253 12.72727273 12.92929293 13.13131313
 13.33333333 13.53535354 13.73737374 13.93939394 14.14141414 14.34343434
 14.54545455 14.74747475 14.94949495 15.15151515 15.35353535 15.55555556
 15.75757576 15.95959596 16.16161616 16.36363636 16

## eye

Return a 2-D array with ones on the diagonal and zeros elsewhere. Also called an identity matrix

Syntax: numpy.eye(R, C, k).

R=Number of Rows.

C=Number of Columns, default: C=R.

k=index of diagonal, default: k=0.

In [17]:
# prints identity matrix 10 x 10 
print(np.eye(10))   # 1st parameter 

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [18]:
print(np.eye(10, k=1))   # diagonal offset by one

[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


## Random 

Numpy has lots of options to create random numbered arrays:

### rand
Create an array of the given shape and populate it with random variables derived from a uniform distribution between `[0, 1)`.

In [19]:
print(np.random.rand(5))   # generate 5 random values

[0.57536207 0.84829957 0.97663233 0.55335997 0.58947217]


In [20]:
print(np.random.rand(3,2))  # generate a random 3x2 matrix 

[[1.14802634e-04 1.34838239e-01]
 [4.35361015e-01 1.30205839e-04]
 [3.20448281e-01 3.49516801e-02]]


### randn

Return a variable (or a set of variables) from the "Standard Normal Distribution". Unlike rand which is from a uniform distribution: 

A standard Normal Distribution has mean 0 and SD of 1 as we know.

In [21]:
print(np.random.randn(5))

[ 1.06079662  0.15991893 -0.69013862 -0.90539603 -1.55742086]


In [22]:
print(np.random.randn(3,2))

[[-1.11578668  0.94810783]
 [ 0.24836128 -0.9864285 ]
 [ 1.16754724  0.74463105]]


### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [23]:
print(np.random.randint(4,size=5))       # Returns one rand integer between the values 0 & 3(4 is excluded)

[2 1 0 2 1]


In [24]:
print(np.random.randint(1,4,size=5))    # Returns  5 rand integers between 1 & 3 (4 is excluded)

[3 1 1 3 3]


In [25]:
print(np.random.randint(1,10,size=(5,5)))    # Returns  5x5 marix of rand integers between 1 & 10 (10 is excluded)

[[4 9 5 1 2]
 [2 5 6 9 5]
 [9 9 1 6 7]
 [7 2 5 3 9]
 [1 9 6 4 7]]


## Attributes of ndarray

Let us look at some important attributes for a ndarray.

In [26]:
# defining some dummy arrays
sample_array=np.arange(30)
print(sample_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [27]:
sample_array_2=np.array([[1,2,3],[4,5,6]])
print(sample_array_2)

[[1 2 3]
 [4 5 6]]


## shape
Shape is an attribute that arrays have. It is not a method.

In [28]:
print(sample_array.shape)   # prints the shape of array

(30,)


In [29]:
print(sample_array_2.shape)

(2, 3)


### size

The total number of elements of the array. Equal to the product of elements of shape

In [30]:
print(sample_array.size)

30


In [31]:
print(sample_array_2.size)

6


### ndim
The number of axes (dimensions) of the array.

In [32]:
print(sample_array.ndim)

1


In [33]:
print(sample_array_2.ndim)

2


## Methods to change shape of an array

### Reshape
Returns the view (in different shape) of original array  with same data

In [34]:
print(sample_array.reshape(5,6))   # used to reshape array

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [35]:
print(sample_array.reshape(3,-1))   # putting -1 as one of the parameters 
                                    #automcatically calculates the parameter if one is provided

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]


### Ravel
Flattens the array

In [36]:
new_array=np.array([[1,2,3],[4,5,6]])

In [37]:
print(new_array)

[[1 2 3]
 [4 5 6]]


In [38]:
b=new_array.ravel()   # note that ravel only returns a "view of the original array".
                      #any change will affect the original array as well
                      # use flatten to avoid this, but flatten consumed more memory and is comparatively slower than ravel
print(b)

[1 2 3 4 5 6]


In [39]:
print(new_array.T)   # transpose

[[1 4]
 [2 5]
 [3 6]]


### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [40]:
rand_array = np.random.randint(0,9,20)   # defining a random array of 20 elements

In [41]:
print(rand_array)

[6 8 2 6 0 5 3 4 0 5 0 8 1 7 0 0 8 6 6 1]


In [42]:
print(rand_array.max())

8


In [43]:
print(rand_array.argmax())  # if multidimensional array, parameter axis can be provided to check max on specific axis

1


In [44]:
print(rand_array.min())

0


In [45]:
print(rand_array.argmin())  # if multidimensional array, parameter axis can be provided to check min on specific axis

4


In [46]:
print(rand_array.sum())

76
