<a href='https://www.hexnbit.com/'> <img src='hexnbit.png'/> </a>

Refer the following documentation for detailed description

https://numpy.org/devdocs/user/quickstart.html

# NumPy Operations

## Arithmetic

Arithmetic operators on arrays apply elementwise.

In [1]:
import numpy as np
arr = np.arange(0,10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [2]:
print(arr + arr)   # adding arr with arr

[ 0  2  4  6  8 10 12 14 16 18]


In [3]:
print(arr * arr)   # multiplying arr with arr

[ 0  1  4  9 16 25 36 49 64 81]


In [4]:
print(arr**3)   # all elements raise to power 3

[  0   1   8  27  64 125 216 343 512 729]


In [5]:
print(arr-arr)

[0 0 0 0 0 0 0 0 0 0]


In [6]:
# Warning on division by zero, but not an error!
# Just replaced with nan  (not a number)
print(arr/arr)

[nan  1.  1.  1.  1.  1.  1.  1.  1.  1.]


C:\Users\Rushil Soni\anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


In [7]:
# Also warning, but not an error instead infinity
print(1/arr)

[       inf 1.         0.5        0.33333333 0.25       0.2
 0.16666667 0.14285714 0.125      0.11111111]


C:\Users\Rushil Soni\anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


In [8]:
print(arr<4)   # print booleans for each element of array suggesting the result of condition

[ True  True  True  True False False False False False False]


## Matrix Operations

In [9]:
A = np.array( [[1,1],
              [0,1]] )
B = np.array( [[2,0],
               [3,4]])

In [10]:
print(A*B)   # elementwise product

[[2 0]
 [0 4]]


In [11]:
print(A@B)  # matrix product

[[5 4]
 [3 4]]


## Universal Array Functions

NumPy provides familiar mathematical functions such as sin, cos, and exp. In NumPy, these are called “universal functions”(ufunc). Within NumPy, these functions operate elementwise on an array, producing an array as output

In [12]:
#Taking Square Roots
print(np.sqrt(arr))    # arr was defined in cell one

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


In [13]:
#Calcualting exponential (e^)
print(np.exp(arr))

[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]


In [14]:
new_arr=np.random.randint(10,20,10)
print(new_arr)
print(np.add(arr,new_arr))

[10 18 16 17 12 10 12 13 19 11]
[10 19 18 20 16 15 18 20 27 20]


In [15]:
print(np.sin(arr))  # radians

[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849]


In [16]:
arr = np.arange(1,10)
print(np.log(arr))  # natural log

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]
