<a href='https://www.hexnbit.com/'> <img src='hexnbit.png'/> </a>

Refer the following documentation for detailed description

https://numpy.org/devdocs/user/quickstart.html

# NumPy Indexing and Selection

Let's us select elements or groups of elements from an array.

In [1]:
import numpy as np

In [2]:
#Creating sample array
arr = np.arange(0,11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


## Indexing and Slicing
Arrays can be indexed, sliced and iterated over, much like lists and other Python sequences.
Slicing in python means taking elements from one given index to another given index.

In [3]:
#Get a value at an index
print(arr[2])

2


In [4]:
#Get values in a range
print(arr[4:8])    # prints every from index 4 thorough 8 (8th index excluded)

[4 5 6 7]


In [5]:
#Get values upto a range
print(arr[:5])

[0 1 2 3 4]


In [6]:
print(arr[2:9:2])   # prints every 2nd value from index 2 thorough 9 (9th index excluded)

[2 4 6 8]


In [7]:
arr[2:6]=999    # sets values of elements at index 2 through 6 to value 999
print(arr)

[  0   1 999 999 999 999   6   7   8   9  10]


In [8]:
# multidimensional array
mul_array=np.arange(15).reshape(5,3)
print(mul_array)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [9]:
print(mul_array[3,2])   # prints element from 3rd row and 2nd column.. (note that numbers start from zero)

11


In [10]:
print(mul_array[2:4,1])  # prints 2nd columns for 2nd row through 4th row (4th row excluded)

[ 7 10]


In [11]:
print(mul_array[2:4,:])  # prints each column for 2nd row through 4th row (4th row excluded)

[[ 6  7  8]
 [ 9 10 11]]


## Boolean Indexing

In [12]:
#Creating sample array
arr = np.arange(0,10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [13]:
mod=[True,False,False,True,True,False,False,True,False,True]
print(arr[mod])   # prints only the indexes which are true

[0 3 4 7 9]


In [14]:
limit=5
above_limit=arr>limit
print(above_limit)     # prints a list of boolean values above limit

[False False False False False False  True  True  True  True]


In [15]:
print(arr[above_limit])    # prints all elements above limit

[6 7 8 9]


In [16]:
# indexing with boolean array
a = np.arange(12).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [17]:
b1 = np.array([False, True,True])    
print(a[b1])           # prints the elements of the rows which are True in b1

[[ 4  5  6  7]
 [ 8  9 10 11]]


## Copy

No Copy, Shallow Copy, Deep Copy

In [18]:
arr=np.arange(10)   # create new array
print(arr)

[0 1 2 3 4 5 6 7 8 9]


### No Copy

In [19]:
new_arr=arr
print(new_arr)
print(new_arr is arr)  # checks if both are same object or not

[0 1 2 3 4 5 6 7 8 9]
True


In [20]:
new_arr[2]=999   # modifying content for new_arr
print(new_arr)

[  0   1 999   3   4   5   6   7   8   9]


In [21]:
print(arr)

[  0   1 999   3   4   5   6   7   8   9]


Note that content for arr has also changed

### Deep Copy

In [22]:
arr=np.arange(10)   # recreating new array
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [23]:
new_arr=arr.copy()
print(new_arr is arr)

False


In [24]:
new_arr[4]=888   # modifying new_arr
print(new_arr)

[  0   1   2   3 888   5   6   7   8   9]


In [25]:
print(arr)

[0 1 2 3 4 5 6 7 8 9]


Note that content for arr has not been changed this time