<a href='https://www.hexnbit.com/'> <img src='hexnbit.png'/> </a>

# A1_Assignment

Mentioned below are the tasks, the solution for each tasks has to be appended by inserting a new cell below the task,
along with the following description:-
1. Why the method was used (if applicable)
2. Explanation of logic

### Task1

- Convert all characters of the word "PYTHON" to its decimal equivalent and then store them.
- Convert all the decimal equvalents back to characters 

**Hint:** Built in functions to do so are there to perform this task
Refer https://docs.python.org/3/library/functions.html

In [1]:
word = "PYTHON"       
decimal_equ=[]
back_to_characters=[]
for letter in word:
    decimal_equ.append(ord(letter))
print(decimal_equ)
    


[80, 89, 84, 72, 79, 78]


### Task2
- Raise 2 to the power 10

In [39]:
n=pow(2, 10)
print(f"2 raised to the power is {n}")  #print statement

2 raised to the power is 1024


### Task3

- From the given list, starting from Japan, print alternate elements
- From the given list, print element at indexes 1,4,5,8 (**Hint**: Use for loop or list comprehension)

In [40]:
# Task 3
list1=["India", "Japan","Singapore","China","Australia","Africa","Dubai","France","Italy","Germany"]
print("alternate elements of list1 starting from Japan:")  
print(list1[1::2])  #print the alternate elements of the list1 using list slicing
print("")


index=[1,4,5,8]      #list containing the desired values
list2=[list1[i] for i in index]     #using list comprehension
print("list of elements at the given index values:")
print(list2)         #print list2

alternate elements of list1 starting from Japan:
['Japan', 'China', 'Africa', 'France', 'Germany']

list of elements at the given index values:
['Japan', 'Australia', 'Africa', 'Italy']


### Task4

- From the given list, extract the "Hex" and print it

In [41]:
# Task 4
list2=[22,[4, [True, False], 6, 8], [888, 999,[111,222,["Hex"]]] ]   #list
print(list2[2][2][2])         #fetching the desired value by index 

['Hex']


### Task5

- From the given dictionary, fetch the keyword "TOPD"

In [42]:
# Task 5
dict1={"Tevatron":["Technologies","Pvt","Ltd",{"Domains":["Embedded","IoT","AI","ML"],"Projects":["inhouse","TOPD"]}]} #dictionary
print(dict1["Tevatron"][3]["Projects"][1])          #print statement

TOPD


### Task6
There are 3 height categories

**167 and below  =**    Short <br>
**168 to 182     =**    Average <br>
**182 and above  =**    Tall<br>

Write a programe which gets the input from user and prints if the category the person fits in

**Hint**: Use function input()

In [3]:
x=int(input("the given number is:"))           
def fun(x):                     #defining function
    if(x<=167):                 #checks if number is less than or equls to 167
        return("Short")
    elif(x>167 and x<=182):     #checks if number is between 167 and 182
        return("Average")
    else:
        return("Tall")           #checks if number is greater than 182
    
nh=fun(x)                        #calling the function 
print(nh)                        #print statement

the given number is:199
Tall


### Task7

Using maximum 2 lines of code, generate all upper case alphabets

**Hint**: Refer ASCII Table

In [61]:
for x in range(65, 91):      #starts from 65 and prints upto 90
    print(chr(x))            #print statement

A
B
C
D
E
F
G
H
I
J
K
L
M
N
O
P
Q
R
S
T
U
V
W
X
Y
Z


### Task8

Generate integers between (100 and 200) both inclusive, using NumPy

In [45]:
import numpy as np
integer=np.arange(100, 201)    #create new array
print(integer)                 #print statement
print(type(integer))        #print type of the array

[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153
 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171
 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189
 190 191 192 193 194 195 196 197 198 199 200]
<class 'numpy.ndarray'>


### Task9

Print all even integers from the array created in Task8

In [46]:
print("All even integers from the array created in Task8:")
integer[0:101:2]           # print even integers from the array

All even integers from the array created in Task8:


array([100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124,
       126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150,
       152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176,
       178, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198, 200])

### Task10

Print all 100 values from Standard Normal Distribution

In [57]:
import numpy as np                       #importing numpy as np
array=np.random.normal(100, 200, 100)    #create array of 100 values from standard normal distribution
print("100 random numbers from a standard normal distribution.")
print(array)
print(type(array))

100 random numbers from a standard normal distribution.
[  62.11205768  350.0206051   103.91272226 -156.87045779   38.53186909
  369.05657756  417.48481951  157.26054113  278.57832373   18.40362001
 -116.16011175  -27.58194401 -100.70382066   36.67689076  -88.69001831
  410.57074807   56.93947177  374.208582   -101.72851848  471.8482271
  -11.13193862  250.09661533  272.39236882  239.67084607  -76.11344836
   98.03500045  281.84192327  488.53455694  115.80184127  323.00565898
  203.23072106   49.87370891  -75.31515864  272.83438835  249.86576412
 -149.14879182  -76.99053131   88.02111546  113.27426961 -368.77550879
   70.56531563  497.62862112 -174.30234155   86.49273031   83.80627525
  428.04806049 -245.04559426   40.15793267  -92.69679798  -54.24253944
  225.24623511   82.16944607   -9.58903899 -325.95075845  -55.73724506
  -89.46250671  156.37136172 -144.81809558  179.60385289  610.32705802
  -81.86766465  106.05283544  395.30643895  303.80912483   12.91025647
  228.56360328  349.31

### Task11

Create a NumPy array of random number, whose dimension attribute is equal to 4

In [44]:
import numpy as np
array=np.random.randint(0,20,4)      #create a array whose dimension attribute is equal to 4
print(array)                        #print array

[15 16 13  9]


### Task12

Create an NumPy array of 100 values evenly spaced between 10 and 20

In [43]:
import numpy as np
print("100 values evenly spaced between 10 and 20")
print(np.linspace(10,20,100))    #array of 100 values evenly spaced between 10 and 20

100 values evenly spaced between 10 and 20
[10.         10.1010101  10.2020202  10.3030303  10.4040404  10.50505051
 10.60606061 10.70707071 10.80808081 10.90909091 11.01010101 11.11111111
 11.21212121 11.31313131 11.41414141 11.51515152 11.61616162 11.71717172
 11.81818182 11.91919192 12.02020202 12.12121212 12.22222222 12.32323232
 12.42424242 12.52525253 12.62626263 12.72727273 12.82828283 12.92929293
 13.03030303 13.13131313 13.23232323 13.33333333 13.43434343 13.53535354
 13.63636364 13.73737374 13.83838384 13.93939394 14.04040404 14.14141414
 14.24242424 14.34343434 14.44444444 14.54545455 14.64646465 14.74747475
 14.84848485 14.94949495 15.05050505 15.15151515 15.25252525 15.35353535
 15.45454545 15.55555556 15.65656566 15.75757576 15.85858586 15.95959596
 16.06060606 16.16161616 16.26262626 16.36363636 16.46464646 16.56565657
 16.66666667 16.76767677 16.86868687 16.96969697 17.07070707 17.17171717
 17.27272727 17.37373737 17.47474747 17.57575758 17.67676768 17.77777778
 17.8787

### Task13

Create a NumPy array of shape 5x5 and print the last 3 rows

In [48]:
import numpy as np                         
mul_array=np.arange(25).reshape(5,5)       # multidimensional array
print(mul_array[2:5,:])


[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


### Task14

Using the array created above in Task13, Print the first 2 columns

In [49]:
print("The first 2 columns of the array created in Task13:")
print(mul_array[:,[0,2]])      # print first 2 columns of the array

The first 2 columns of the array created in Task13:
[[ 0  2]
 [ 5  7]
 [10 12]
 [15 17]
 [20 22]]


### Task15

Create an array of 25 random values
- Find the sum of all elements
- Print the element with maximum value and minimum value

In [51]:
import numpy as np               #importing numpy as np
rand_num=np.random.rand(25)      #create array of 25 random values
print("array of 25 random values:")
print(rand_num)
print("sum of all the elements:")  
print(np.sum(rand_num))           #sum of all the elements of array
print("element with maximum value:")
print(np.amax(rand_num))           # maximum value of the array 
print("element with minimum value:")
print(np.amin(rand_num))           #minimum value of the array

array of 25 random values:
[0.10696575 0.76102762 0.96196913 0.157008   0.14457373 0.47154263
 0.35548985 0.15956002 0.80615718 0.84520779 0.66552297 0.63428877
 0.23473198 0.18660319 0.21954417 0.29192485 0.01328291 0.51923889
 0.53736881 0.12456421 0.59068903 0.81445628 0.77273822 0.07224865
 0.02735108]
sum of all the elements:
10.474055720717697
element with maximum value:
0.9619691334849126
element with minimum value:
0.013282911667532482


### Task16

In the array created above, print columns with indexes 1,3,4 without directly indexing them <br>
**Hint:** Make use of another list for indexing

In [12]:
list2=[i in (1,3,4) for i in range(0,25)]     #list comprehension
rand_num[list2]

array([0.66998991, 0.77436063, 0.97055262])

### Task17
Read car_sales.csv

In [21]:
import pandas as pd             #importing pandas as pd
car_sales=pd.read_csv("car_sales.csv")
car_sales.head(5)

Unnamed: 0 Manufacturer    Model     Type  Min.Price  Price  Max.Price  \
0           1        Acura  Integra    Small       12.9   15.9       18.8   
1           2        Acura   Legend  Midsize       29.2   33.9       38.7   
2           3         Audi       90  Compact       25.9   29.1       32.3   
3           4         Audi      100  Midsize       30.8   37.7       44.6   
4           5          BMW     535i  Midsize       23.7   30.0       36.2   

   MPG.city  MPG.highway             AirBags  ... Passengers Length  \
0        25           31                None  ...          5    177   
1        18           25  Driver & Passenger  ...          5    195   
2        20           26         Driver only  ...          5    180   
3        19           26  Driver & Passenger  ...          6    193   
4        22           30         Driver only  ...          4    186   

   Wheelbase  Width  Turn.circle  Rear.seat.room Luggage.room  Weight  \
0        102     68           37            26.5         11.0    2705   
1        115     71           38            30.0         15.0    3560   
2        102     67           37            28.0         14.0    3375   
3        106     70           37            31.0         17.0    3405   
4        109     69           39            27.0         13.0    3640   

    Origin           Make  
0  non-USA  Acura Integra  
1  non-USA   Acura Legend  
2  non-USA        Audi 90  
3  non-USA       Audi 100  
4  non-USA       BMW 535i  

[5 rows x 28 columns]

### Task18
Sort data frame in ascending order of the Price column

In [56]:
ascending = car_sales["Price"].sort_values()      #sorting the data frame in ascending order of the price column
ascending.head()

30    7.4
43    8.0
52    8.3
38    8.4
79    8.4
Name: Price, dtype: float64

### Task19
Print number of unique car manufacturers in the data

In [53]:
car_sales.Manufacturer.nunique()          #number of unique car manufacturers

32

### Task20
Print the maximum Wheelbase from the data

In [54]:
car_sales.Wheelbase.max()         #maximum wheelbase 

119

### Task21
Print the car Model which has maximum Wheelbase

In [55]:
car_sales.groupby("Model").Wheelbase.max().idxmax(axis=0)   #groupby Model which has maximum wheelbase

'Aerostar'

### Task22

Print the Details of car with maximum passenger capacity

In [27]:
var1=car_sales.groupby("Model").Passengers.max().idxmax(0)
var2=car_sales.set_index("Model")
var2.loc["Aerostar"]             # multirow and multicolumn indexing

Unnamed: 0                       36
Manufacturer                   Ford
Type                            Van
Min.Price                      14.5
Price                          19.9
Max.Price                      25.3
MPG.city                         15
MPG.highway                      20
AirBags                 Driver only
DriveTrain                      4WD
Cylinders                         6
EngineSize                        3
Horsepower                      145
RPM                            4800
Rev.per.mile                   2080
Man.trans.avail                 Yes
Fuel.tank.capacity               21
Passengers                        7
Length                          176
Wheelbase                       119
Width                            72
Turn.circle                      45
Rear.seat.room                   30
Luggage.room                    NaN
Weight                         3735
Origin                          USA
Make                  Ford Aerostar
Name: Aerostar, dtype: objec