<a href='https://www.hexnbit.com/'> <img src='hexnbit.png'/> </a>

# DataFrames

We can say that dataframes are basically collection of Pandas Series which share the same indexes

In [1]:
import numpy as np
import pandas as pd

In [2]:
num_data=np.arange(25).reshape(5,5)  # defining an array of shape 5 x 4 (4 rows, 5 columns)
print(num_data)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


## Creating Data Frames

In [3]:
frame=pd.DataFrame(data=num_data,index=["R1","R2","R3","R4","R5"],columns=["C1","C2","C3","C4","C5"])   
# converting the above defined NumPy array to pandas data frame by providing index and columns
print(frame)                                                               

    C1  C2  C3  C4  C5
R1   0   1   2   3   4
R2   5   6   7   8   9
R3  10  11  12  13  14
R4  15  16  17  18  19
R5  20  21  22  23  24


In [4]:
# same can be done without mentioning the data, index and columns keyword #but needs to be in the correct order
frame=pd.DataFrame(num_data,["R1","R2","R3","R4","R5"],["C1","C2","C3","C4","C5"])
print(frame)  
print(type(frame))

    C1  C2  C3  C4  C5
R1   0   1   2   3   4
R2   5   6   7   8   9
R3  10  11  12  13  14
R4  15  16  17  18  19
R5  20  21  22  23  24
<class 'pandas.core.frame.DataFrame'>


## Indexing Data Frames

### Column Indexing

In [5]:
print(frame["C3"])   # fetching complete column data from a Data Frame

R1     2
R2     7
R3    12
R4    17
R5    22
Name: C3, dtype: int32


In [6]:
print(type(frame["C3"]))  # dataframe is a collection of series

<class 'pandas.core.series.Series'>


In [7]:
print(frame[["C1","C3"]])   # fetching multiple column data from a Data Frame

    C1  C3
R1   0   2
R2   5   7
R3  10  12
R4  15  17
R5  20  22


In [8]:
print(frame.iloc[:,[0,1]])

    C1  C2
R1   0   1
R2   5   6
R3  10  11
R4  15  16
R5  20  21


### Row Indexing

In [9]:
print(frame.loc["R1"])

C1    0
C2    1
C3    2
C4    3
C5    4
Name: R1, dtype: int32


In [10]:
print(frame.loc[["R1","R3"]])   # Multiple Rows

    C1  C2  C3  C4  C5
R1   0   1   2   3   4
R3  10  11  12  13  14


In [11]:
print(frame.iloc[0])    # can also be done using index number

C1    0
C2    1
C3    2
C4    3
C5    4
Name: R1, dtype: int32


### Row and Column Indexing

In [12]:
print(frame.loc["R2","C3"])   # Single Row and Single Column Indexing

7


In [13]:
print(frame.loc[["R2","R4"],["C3","C5"]])   # Multi Row and Multi Column Indexing

    C3  C5
R2   7   9
R4  17  19


### Creating New Columns

In [14]:
frame["C6"]=[100,200,300,400,500]
print(frame)

    C1  C2  C3  C4  C5   C6
R1   0   1   2   3   4  100
R2   5   6   7   8   9  200
R3  10  11  12  13  14  300
R4  15  16  17  18  19  400
R5  20  21  22  23  24  500


### Deleting Columns

In [15]:
# Temporary Drop
frame.drop(["C6"],axis=1)   # Axis =1 means Columns

C1  C2  C3  C4  C5
R1   0   1   2   3   4
R2   5   6   7   8   9
R3  10  11  12  13  14
R4  15  16  17  18  19
R5  20  21  22  23  24

In [16]:
print(frame)   # Drop not reflected in the frame

    C1  C2  C3  C4  C5   C6
R1   0   1   2   3   4  100
R2   5   6   7   8   9  200
R3  10  11  12  13  14  300
R4  15  16  17  18  19  400
R5  20  21  22  23  24  500


In [17]:
# Permanent Drop using inplace parameter as True
frame.drop(["C6"],axis=1,inplace=True)

In [18]:
print(frame)   # Drop reflected in frame, hence permanent

    C1  C2  C3  C4  C5
R1   0   1   2   3   4
R2   5   6   7   8   9
R3  10  11  12  13  14
R4  15  16  17  18  19
R5  20  21  22  23  24


### Creating New Rows

In [19]:
frame.loc["R6"]=[99,99,99,99,99]
print(frame)

    C1  C2  C3  C4  C5
R1   0   1   2   3   4
R2   5   6   7   8   9
R3  10  11  12  13  14
R4  15  16  17  18  19
R5  20  21  22  23  24
R6  99  99  99  99  99


### Deleting Rows

In [20]:
# Temporary Deletion
frame.drop(["R6"])    # or frame.drop(["R6"],axis=0), but axis is by default equal to zero

C1  C2  C3  C4  C5
R1   0   1   2   3   4
R2   5   6   7   8   9
R3  10  11  12  13  14
R4  15  16  17  18  19
R5  20  21  22  23  24

In [21]:
print(frame)  # Not reflected in frame

    C1  C2  C3  C4  C5
R1   0   1   2   3   4
R2   5   6   7   8   9
R3  10  11  12  13  14
R4  15  16  17  18  19
R5  20  21  22  23  24
R6  99  99  99  99  99


In [22]:
# Permanent Deletion
frame.drop(["R6"],inplace=True)

In [23]:
print(frame)   # deletion reflected

    C1  C2  C3  C4  C5
R1   0   1   2   3   4
R2   5   6   7   8   9
R3  10  11  12  13  14
R4  15  16  17  18  19
R5  20  21  22  23  24


### Conditional Indexing

In [24]:
print([frame>10])       # print all booleans for frame elements with condition where element is greater than 10

[       C1     C2     C3     C4     C5
R1  False  False  False  False  False
R2  False  False  False  False  False
R3  False   True   True   True   True
R4   True   True   True   True   True
R5   True   True   True   True   True]


In [25]:
print(frame[frame>10])  # print all elements of frame which are greater than 10

      C1    C2    C3    C4    C5
R1   NaN   NaN   NaN   NaN   NaN
R2   NaN   NaN   NaN   NaN   NaN
R3   NaN  11.0  12.0  13.0  14.0
R4  15.0  16.0  17.0  18.0  19.0
R5  20.0  21.0  22.0  23.0  24.0


In [26]:
print([frame["C2"]>6])  # print booleans for elements of Column C2 with condition that elements are greater than 6

[R1    False
R2    False
R3     True
R4     True
R5     True
Name: C2, dtype: bool]


In [27]:
print(frame[frame["C2"]>6])  # print all rows for which "C2">6 is true

    C1  C2  C3  C4  C5
R3  10  11  12  13  14
R4  15  16  17  18  19
R5  20  21  22  23  24


In [28]:
print(frame[frame["C2"]>6]["C2"])  # print all rows of C2 for which "C2">6 is true

R3    11
R4    16
R5    21
Name: C2, dtype: int64


In [29]:
print(frame[(frame["C2"]>6) & (frame["C3"]>12)])  # print rows for which C2>6 and C3 greater than 12
# similarly | "bitwise OR operator" or "Pipe Operator" can be used 

    C1  C2  C3  C4  C5
R4  15  16  17  18  19
R5  20  21  22  23  24


## Index Manipulation

In [30]:
print(frame)
print(frame.reset_index())  # temporary reset, use inplace for permanent reset and axis number to select axis of reset
#print(frame.reset_index(inplace=True))

    C1  C2  C3  C4  C5
R1   0   1   2   3   4
R2   5   6   7   8   9
R3  10  11  12  13  14
R4  15  16  17  18  19
R5  20  21  22  23  24
  index  C1  C2  C3  C4  C5
0    R1   0   1   2   3   4
1    R2   5   6   7   8   9
2    R3  10  11  12  13  14
3    R4  15  16  17  18  19
4    R5  20  21  22  23  24


In [31]:
frame["new"]=["R11","R22","R33","R44","R55"]    # adding new column to frame which will be later used as new Index
print(frame)

    C1  C2  C3  C4  C5  new
R1   0   1   2   3   4  R11
R2   5   6   7   8   9  R22
R3  10  11  12  13  14  R33
R4  15  16  17  18  19  R44
R5  20  21  22  23  24  R55


In [32]:
frame.set_index("new")    # Temporary Index Change

C1  C2  C3  C4  C5
new                    
R11   0   1   2   3   4
R22   5   6   7   8   9
R33  10  11  12  13  14
R44  15  16  17  18  19
R55  20  21  22  23  24

In [33]:
print(frame)   # Change not reflected yet

    C1  C2  C3  C4  C5  new
R1   0   1   2   3   4  R11
R2   5   6   7   8   9  R22
R3  10  11  12  13  14  R33
R4  15  16  17  18  19  R44
R5  20  21  22  23  24  R55


In [34]:
frame.set_index("new",inplace=True)   # Permanent index change

In [35]:
print(frame)   # Change reflected

     C1  C2  C3  C4  C5
new                    
R11   0   1   2   3   4
R22   5   6   7   8   9
R33  10  11  12  13  14
R44  15  16  17  18  19
R55  20  21  22  23  24


In [36]:
print(frame.axes)   # print axes

[Index(['R11', 'R22', 'R33', 'R44', 'R55'], dtype='object', name='new'), Index(['C1', 'C2', 'C3', 'C4', 'C5'], dtype='object')]


In [37]:
frame.rename_axis("Columns",axis=1,inplace=True)  # permanently change names of axes
frame.rename_axis("Rows",axis=0, inplace=True)

In [38]:
print(frame)

Columns  C1  C2  C3  C4  C5
Rows                       
R11       0   1   2   3   4
R22       5   6   7   8   9
R33      10  11  12  13  14
R44      15  16  17  18  19
R55      20  21  22  23  24


In [39]:
frame.columns=["a","b","c","d","e"]

In [40]:
print(frame)

       a   b   c   d   e
Rows                    
R11    0   1   2   3   4
R22    5   6   7   8   9
R33   10  11  12  13  14
R44   15  16  17  18  19
R55   20  21  22  23  24
