<a href='https://www.hexnbit.com/'> <img src='hexnbit.png'/> </a>

# Operations

In [1]:
import numpy as np
import pandas as pd

In [2]:
# creating random test_data to show operations
test_data=np.random.randint(0,9,size=(5,5))
print(test_data)

[[4 0 1 0 1]
 [8 0 8 6 4]
 [3 0 4 6 8]
 [1 8 4 1 3]
 [6 5 3 6 1]]


In [3]:
# creating data frame from above array
data_frame=pd.DataFrame(test_data,index="R1 R2 R3 R4 R5".split(),columns="C1 C2 C3 C4 C5".split())
data_frame

C1  C2  C3  C4  C5
R1   4   0   1   0   1
R2   8   0   8   6   4
R3   3   0   4   6   8
R4   1   8   4   1   3
R5   6   5   3   6   1

In [4]:
# in order to add column containing string data- to see an operation based on string data
data_frame["C6"]=["Hex","N","Bit","AI","ML"]
data_frame

C1  C2  C3  C4  C5   C6
R1   4   0   1   0   1  Hex
R2   8   0   8   6   4    N
R3   3   0   4   6   8  Bit
R4   1   8   4   1   3   AI
R5   6   5   3   6   1   ML

In [5]:
# head function shows the above few rows of the data frame
# number of rows to be displayed can be input by user
data_frame.head(2)  #  prints n number of rows 

C1  C2  C3  C4  C5   C6
R1   4   0   1   0   1  Hex
R2   8   0   8   6   4    N

In [ ]:
data_frame  # printing for reference

In [6]:
# number of unique values in column C4
print(data_frame["C4"].nunique())

3


In [7]:
# unique values in column C4
print(data_frame["C4"].unique())

[0 6 1]


In [8]:
# another way to print number of unique values in column C4
print(len(data_frame["C4"].unique()))

3


In [9]:
# print repetition count of each number
print(data_frame["C4"].value_counts())

6    3
1    1
0    1
Name: C4, dtype: int64


### User Defined Functions on Pandas Data

In [ ]:
# printing mean of column C4
print(data_frame["C4"].mean())

In [10]:
# user defined function to multiply data by 10
def multiply_ten(var):
    return var*10

In [11]:
# applying user defined function on elemets of C4
data_frame["C4"].apply(multiply_ten) # you can also use use a lambda function

R1     0
R2    60
R3    60
R4    10
R5    60
Name: C4, dtype: int64

In [12]:
data_frame # printing again for referece

C1  C2  C3  C4  C5   C6
R1   4   0   1   0   1  Hex
R2   8   0   8   6   4    N
R3   3   0   4   6   8  Bit
R4   1   8   4   1   3   AI
R5   6   5   3   6   1   ML

In [13]:
# checking length of each string element in column C6
print(data_frame["C6"].apply(len))

R1    3
R2    1
R3    3
R4    2
R5    2
Name: C6, dtype: int64


In [15]:
# Sorting data frame based on column C5
#data_frame.sort_values("C5")
data_frame.sort_values("C5",ascending=False)

C1  C2  C3  C4  C5   C6
R3   3   0   4   6   8  Bit
R2   8   0   8   6   4    N
R4   1   8   4   1   3   AI
R1   4   0   1   0   1  Hex
R5   6   5   3   6   1   ML

In [16]:
# Sorting data frame based on Row2, C6 has been dropped as it contained string data
data_frame.drop("C6",axis=1).sort_values(by="R2",axis=1)

C2  C5  C4  C1  C3
R1   0   1   0   4   1
R2   0   4   6   8   8
R3   0   8   6   3   4
R4   8   3   1   1   4
R5   5   1   6   6   3

In [17]:
# checking if any element in data frame is null
data_frame.isnull()

C1     C2     C3     C4     C5     C6
R1  False  False  False  False  False  False
R2  False  False  False  False  False  False
R3  False  False  False  False  False  False
R4  False  False  False  False  False  False
R5  False  False  False  False  False  False